// Generated by scripts/update-matvaretabellen.mjs. Do not edit manually.
export const foodDataSource = {
  name: "Matvaretabellen 2026",
  url: "https://www.matvaretabellen.no/api/nb/foods.json",
  retrievedAt: "2026-07-25",
} as const;

export const foods = [
  {
    "id": "01.028",
    "name": "Cottage cheese",
    "uri": "https://www.matvaretabellen.no/cottage-cheese/",
    "per100g": {
      "calories": 97,
      "protein": 13,
      "fat": 4.3,
      "carbs": 1.5
    }
  },
  {
    "id": "02.001",
    "name": "Egg, rå",
    "uri": "https://www.matvaretabellen.no/egg-ra/",
    "per100g": {
      "calories": 149,
      "protein": 13,
      "fat": 10.7,
      "carbs": 0.3
    }
  },
  {
    "id": "03.004",
    "name": "Kalkun, kjøtt med skinn, rå",
    "uri": "https://www.matvaretabellen.no/kalkun-kjott-med-skinn-ra/",
    "per100g": {
      "calories": 133,
      "protein": 21.6,
      "fat": 5.2,
      "carbs": 0
    }
  },
  {
    "id": "03.054",
    "name": "Storfe, entrecôte, rå",
    "uri": "https://www.matvaretabellen.no/storfe-entrecote-ra/",
    "per100g": {
      "calories": 186,
      "protein": 20.6,
      "fat": 11.5,
      "carbs": 0
    }
  },
  {
    "id": "03.066",
    "name": "Storfe, ytrefilet, rå",
    "uri": "https://www.matvaretabellen.no/storfe-ytrefilet-ra/",
    "per100g": {
      "calories": 118,
      "protein": 22.5,
      "fat": 3.1,
      "carbs": 0
    }
  },
  {
    "id": "03.126",
    "name": "Karbonadedeig, storfe, 4,5 % fett, rå",
    "uri": "https://www.matvaretabellen.no/karbonadedeig-storfe-4-5-fett-ra/",
    "per100g": {
      "calories": 123,
      "protein": 20.7,
      "fat": 4.5,
      "carbs": 0
    }
  },
  {
    "id": "03.205",
    "name": "Kylling, filet, uten skinn, rå",
    "uri": "https://www.matvaretabellen.no/kylling-filet-uten-skinn-ra/",
    "per100g": {
      "calories": 111,
      "protein": 23,
      "fat": 2.1,
      "carbs": 0
    }
  },
  {
    "id": "03.332",
    "name": "Kylling, lår (overlår og lårklubbe), uten skinn, rå",
    "uri": "https://www.matvaretabellen.no/kylling-lar-overlar-og-larklubbe-uten-skinn-ra/",
    "per100g": {
      "calories": 131,
      "protein": 18,
      "fat": 6.6,
      "carbs": 0
    }
  },
  {
    "id": "04.015",
    "name": "Laks, vill, rå",
    "uri": "https://www.matvaretabellen.no/laks-vill-ra/",
    "per100g": {
      "calories": 182,
      "protein": 19.7,
      "fat": 11.5,
      "carbs": 0
    }
  },
  {
    "id": "04.107",
    "name": "Tunfisk, i olje, avrent, hermetisk",
    "uri": "https://www.matvaretabellen.no/tunfisk-i-olje-avrent-hermetisk/",
    "per100g": {
      "calories": 128,
      "protein": 24.6,
      "fat": 3.3,
      "carbs": 0
    }
  },
  {
    "id": "04.322",
    "name": "Brisling, i olje, avrent, hermetisk",
    "uri": "https://www.matvaretabellen.no/brisling-i-olje-avrent-hermetisk/",
    "per100g": {
      "calories": 261,
      "protein": 18.3,
      "fat": 20.9,
      "carbs": 0
    }
  },
  {
    "id": "04.387",
    "name": "Reker, rå",
    "uri": "https://www.matvaretabellen.no/reker-ra/",
    "per100g": {
      "calories": 102,
      "protein": 21,
      "fat": 2,
      "carbs": 0
    }
  },
  {
    "id": "05.030",
    "name": "Sesamfrø, med skall",
    "uri": "https://www.matvaretabellen.no/sesamfro-med-skall/",
    "per100g": {
      "calories": 595,
      "protein": 19.6,
      "fat": 53.8,
      "carbs": 1.4
    }
  },
  {
    "id": "05.340",
    "name": "Ris, villris, kokt",
    "uri": "https://www.matvaretabellen.no/ris-villris-kokt/",
    "per100g": {
      "calories": 114,
      "protein": 4.5,
      "fat": 0.3,
      "carbs": 22.2
    }
  },
  {
    "id": "05.420",
    "name": "Mandelmel",
    "uri": "https://www.matvaretabellen.no/mandelmel/",
    "per100g": {
      "calories": 603,
      "protein": 22.4,
      "fat": 53.1,
      "carbs": 4
    }
  },
  {
    "id": "06.010",
    "name": "Agurk, norsk, rå",
    "uri": "https://www.matvaretabellen.no/agurk-norsk-ra/",
    "per100g": {
      "calories": 9,
      "protein": 0.8,
      "fat": 0,
      "carbs": 1.3
    }
  },
  {
    "id": "06.016",
    "name": "Blomkål, norsk, rå",
    "uri": "https://www.matvaretabellen.no/blomkal-norsk-ra/",
    "per100g": {
      "calories": 19,
      "protein": 1.7,
      "fat": 0,
      "carbs": 2.4
    }
  },
  {
    "id": "06.018",
    "name": "Brokkoli, norsk, rå",
    "uri": "https://www.matvaretabellen.no/brokkoli-norsk-ra/",
    "per100g": {
      "calories": 24,
      "protein": 2.9,
      "fat": 0,
      "carbs": 2
    }
  },
  {
    "id": "06.035",
    "name": "Grønnkål, rå",
    "uri": "https://www.matvaretabellen.no/gronnkal-ra/",
    "per100g": {
      "calories": 36,
      "protein": 3.3,
      "fat": 0.7,
      "carbs": 2.2
    }
  },
  {
    "id": "06.036",
    "name": "Gulrot, norsk, rå",
    "uri": "https://www.matvaretabellen.no/gulrot-norsk-ra/",
    "per100g": {
      "calories": 25,
      "protein": 0,
      "fat": 0,
      "carbs": 5.3
    }
  },
  {
    "id": "06.038",
    "name": "Hvitløk, rå",
    "uri": "https://www.matvaretabellen.no/hvitlok-ra/",
    "per100g": {
      "calories": 106,
      "protein": 7.9,
      "fat": 0.6,
      "carbs": 16.3
    }
  },
  {
    "id": "06.042",
    "name": "Løk, gul, norsk, rå",
    "uri": "https://www.matvaretabellen.no/lok-gul-norsk-ra/",
    "per100g": {
      "calories": 30,
      "protein": 1,
      "fat": 0,
      "carbs": 4.4
    }
  },
  {
    "id": "06.048",
    "name": "Paprika, rød, rå",
    "uri": "https://www.matvaretabellen.no/paprika-rod-ra/",
    "per100g": {
      "calories": 26,
      "protein": 0.8,
      "fat": 0.2,
      "carbs": 4.2
    }
  },
  {
    "id": "06.062",
    "name": "Sjampinjong, champignon, rå",
    "uri": "https://www.matvaretabellen.no/sjampinjong-champignon-ra/",
    "per100g": {
      "calories": 17,
      "protein": 2.3,
      "fat": 0.1,
      "carbs": 0.1
    }
  },
  {
    "id": "06.064",
    "name": "Spinat, rå",
    "uri": "https://www.matvaretabellen.no/spinat-ra/",
    "per100g": {
      "calories": 17,
      "protein": 2.8,
      "fat": 0,
      "carbs": 0.1
    }
  },
  {
    "id": "06.085",
    "name": "Squash, zucchini, rå",
    "uri": "https://www.matvaretabellen.no/squash-zucchini-ra/",
    "per100g": {
      "calories": 17,
      "protein": 1.3,
      "fat": 0.1,
      "carbs": 2.2
    }
  },
  {
    "id": "06.093",
    "name": "Rødkål, rå",
    "uri": "https://www.matvaretabellen.no/rodkal-ra/",
    "per100g": {
      "calories": 23,
      "protein": 1.3,
      "fat": 0,
      "carbs": 3.4
    }
  },
  {
    "id": "06.136",
    "name": "Søtpotet, rå",
    "uri": "https://www.matvaretabellen.no/sotpotet-ra/",
    "per100g": {
      "calories": 80,
      "protein": 1.6,
      "fat": 0.1,
      "carbs": 16.8
    }
  },
  {
    "id": "06.138",
    "name": "Romanosalat, rå",
    "uri": "https://www.matvaretabellen.no/romanosalat-ra/",
    "per100g": {
      "calories": 15,
      "protein": 1.2,
      "fat": 0,
      "carbs": 1.4
    }
  },
  {
    "id": "06.207",
    "name": "Hjertesalat, rå",
    "uri": "https://www.matvaretabellen.no/hjertesalat-ra/",
    "per100g": {
      "calories": 14,
      "protein": 1.6,
      "fat": 0,
      "carbs": 1.1
    }
  },
  {
    "id": "06.262",
    "name": "Potet, høstpotet, kokt",
    "uri": "https://www.matvaretabellen.no/potet-hostpotet-kokt/",
    "per100g": {
      "calories": 84,
      "protein": 2.1,
      "fat": 0.1,
      "carbs": 17.8
    }
  },
  {
    "id": "06.502",
    "name": "Blåbær, rå",
    "uri": "https://www.matvaretabellen.no/blabaer-ra/",
    "per100g": {
      "calories": 51,
      "protein": 1,
      "fat": 0.9,
      "carbs": 7.5
    }
  },
  {
    "id": "06.524",
    "name": "Avokado, rå",
    "uri": "https://www.matvaretabellen.no/avokado-ra/",
    "per100g": {
      "calories": 191,
      "protein": 1.8,
      "fat": 19.6,
      "carbs": 0.4
    }
  },
  {
    "id": "06.525",
    "name": "Banan, rå",
    "uri": "https://www.matvaretabellen.no/banan-ra/",
    "per100g": {
      "calories": 88,
      "protein": 1.1,
      "fat": 0.2,
      "carbs": 19.7
    }
  },
  {
    "id": "06.560",
    "name": "Valnøtter",
    "uri": "https://www.matvaretabellen.no/valnotter/",
    "per100g": {
      "calories": 680,
      "protein": 14.1,
      "fat": 66.5,
      "carbs": 2.8
    }
  },
  {
    "id": "06.615",
    "name": "Quinoa, tørr",
    "uri": "https://www.matvaretabellen.no/quinoa-torr/",
    "per100g": {
      "calories": 348,
      "protein": 13.9,
      "fat": 6.7,
      "carbs": 52.2
    }
  },
  {
    "id": "06.616",
    "name": "Quinoa, kokt",
    "uri": "https://www.matvaretabellen.no/quinoa-kokt/",
    "per100g": {
      "calories": 139,
      "protein": 5.6,
      "fat": 2.7,
      "carbs": 20.9
    }
  },
  {
    "id": "06.701",
    "name": "Kokosmelk, hermetisk",
    "uri": "https://www.matvaretabellen.no/kokosmelk-hermetisk/",
    "per100g": {
      "calories": 209,
      "protein": 2,
      "fat": 21.3,
      "carbs": 1.5
    }
  },
  {
    "id": "06.752",
    "name": "Cherrytomat, importert, rå",
    "uri": "https://www.matvaretabellen.no/cherrytomat-importert-ra/",
    "per100g": {
      "calories": 17,
      "protein": 0.6,
      "fat": 0.2,
      "carbs": 2.5
    }
  },
  {
    "id": "08.112",
    "name": "Olivenolje, extra virgin, jomfruolje",
    "uri": "https://www.matvaretabellen.no/olivenolje-extra-virgin-jomfruolje/",
    "per100g": {
      "calories": 889,
      "protein": 0,
      "fat": 98.8,
      "carbs": 0
    }
  },
  {
    "id": "08.249",
    "name": "Kokosolje",
    "uri": "https://www.matvaretabellen.no/kokosolje/",
    "per100g": {
      "calories": 894,
      "protein": 0,
      "fat": 99.3,
      "carbs": 0
    }
  },
  {
    "id": "08.252",
    "name": "Ghee",
    "uri": "https://www.matvaretabellen.no/ghee/",
    "per100g": {
      "calories": 897,
      "protein": 0.3,
      "fat": 99.5,
      "carbs": 0
    }
  },
  {
    "id": "09.003",
    "name": "Honning",
    "uri": "https://www.matvaretabellen.no/honning/",
    "per100g": {
      "calories": 317,
      "protein": 0.3,
      "fat": 0,
      "carbs": 78.9
    }
  }
] as const;
